### ISSUE TITLE
How to build *.a files in wasm-libs

### ISSUE THREAD

**Issue by ChingCdesu** [jedisct1/rust-ffmpeg-wasi#2]
Hi, jedisct.

Could you tell me how to build *.a files by myself, because I want to enable SIMD to make wasm run faster.

Thanks.

**Comment by jedisct1** [comment]
Instructions are here: https://github.com/jedisct1/tinyglitch even though they need to be updated to use `zig cc` instead of requiring the installation of another toolchain.

`ffmpeg` and its dependencies use assembly code and architecture-specific intrinsics for vectorized implementations. 

So, enabling SIMD is unlikely to provide any sensible speed improvement. The code needs to be rewritten specifically for WebAssembly, or to a language with generic vector instructions.

**Comment by ChingCdesu** [comment]
I got `*.a` files successfully. Thanks a lot.
